// Golondrina Airene M

package edu.uep.cos.attendance.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "students")
public class Student {

    // Primary key for students table (auto-incremented)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "student_id")
    private Integer studentId;

    // Unique student number used for identification
    @Column(name = "student_number")
    private String studentNumber;

    // Stores the student's password (hashed if used for login)
    private String password;

    // Student's first name
    @Column(name = "first_name")
    private String firstName;

    // Student's last name
    @Column(name = "last_name")
    private String lastName;

    // Foreign key reference to the course the student belongs to
    @Column(name = "course_id")
    private Integer courseId;

    // Student's academic year level
    @Column(name = "year_level")
    private Integer yearLevel;

    // Timestamp when the record was created (auto-generated by DB)
    @Column(name = "created_at", insertable = false, updatable = false)
    private LocalDateTime createdAt;
}
